apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
  labels:
    app: userapi
spec:
  replicas: 2
  minReadySeconds: 20
  progressDeadlineSeconds: 100
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      containers:
        - name: userapi
          image: souvikdas81/userapi:1.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"