apiVersion: v1
kind: Service
metadata:
  name: userapi-service
  labels:
    name: userapi-service
spec:
  type: LoadBalancer
  selector:
    app: userapi
  ports:
    - port: 8081
      targetPort: 8081